### ISSUE TITLE
Support 16 kb page sizes for newer targets

### ISSUE THREAD

**Issue by jonatino** [bbqsrc/cargo-ndk#167]
![Image](https://github.com/user-attachments/assets/0fd603be-578f-499f-a099-00addc9947c3)

https://developer.android.com/guide/practices/page-sizes

**Comment by bbqsrc** [comment]
Patch?

**Comment by middagj** [comment]
Using NDK r28 solves this automatically

**Comment by appdev** [comment]
> [@middagj](https://github.com/middagj) yup you're right. I was using 27 still.是的，你说得对。我还在用 27。
> 
> If anyone wants to fix this with older versions than r28 just use these flags如果有人想用比 r28 更旧的版本修复这个问题，只需使用这些标志
> 
> ```
> [target.aarch64-linux-android]
> rustflags = [
>     "-C", "link-arg=-Wl,-z,max-page-size=16384",
> ]
> 
> [target.x86_64-linux-android]
> rustflags = [
>     "-C", "link-arg=-Wl,-z,max-page-size=16384",
> ]
> ```

Has anyone successfully used this configuration with cargo ndk to compile a library that supports a 16KB page size?
I tried compiling it, but when I check the output with readelf -l xxx.so, it still shows 4K alignment.


```` toml

[target.aarch64-linux-android]
rustflags = [
    "-C", "link-arg=-Wl,-z,max-page-size=16384",
]
[target.armv7-linux-androideabi]
rustflags = [
    "-C", "link-arg=-Wl,-z,max-page-size=16384",
]

```
